<template>
    <!-- eslint-disable -->
    <div class="block__body">
        <a17-locale type="a17-textfield" :attributes="{ label: 'Label', name: fieldName('label'), type: 'text', required: true, inStore: 'value' }" ></a17-locale><a17-locale type="a17-textfield" :attributes="{ label: 'Help text', name: fieldName('help'), type: 'text', note: 'Extra information, visible to the user', inStore: 'value' }" ></a17-locale><a17-vselect label="Type" :name="fieldName('type')" :options='[{&quot;value&quot;:&quot;text&quot;,&quot;label&quot;:&quot;Text&quot;},{&quot;value&quot;:&quot;textarea&quot;,&quot;label&quot;:&quot;Textarea&quot;},{&quot;value&quot;:&quot;url&quot;,&quot;label&quot;:&quot;URL&quot;},{&quot;value&quot;:&quot;email&quot;,&quot;label&quot;:&quot;Email&quot;},{&quot;value&quot;:&quot;number&quot;,&quot;label&quot;:&quot;Number&quot;},{&quot;value&quot;:&quot;date&quot;,&quot;label&quot;:&quot;Date&quot;},{&quot;value&quot;:&quot;file&quot;,&quot;label&quot;:&quot;File&quot;}]' :selected="{&quot;value&quot;:&quot;text&quot;,&quot;label&quot;:&quot;Text&quot;}" :has-default-store="true" size="large" in-store="inputValue" > </a17-vselect><a17-vselect label="Required" :name="fieldName('required')" :options='[{&quot;value&quot;:0,&quot;label&quot;:&quot;No&quot;},{&quot;value&quot;:1,&quot;label&quot;:&quot;Yes&quot;}]' :selected="{&quot;value&quot;:1,&quot;label&quot;:&quot;Yes&quot;}" :has-default-store="true" size="large" in-store="inputValue" > </a17-vselect><a17-connectorfield :is-value-equal="true" :keep-alive="true" :field-name="fieldName('type')" :required-field-values="'text'" > <a17-textfield label="Maximum length" :name="fieldName('maxLength')" type="number" note="Number of characters" in-store="value" ></a17-textfield></a17-connectorfield><a17-connectorfield :is-value-equal="true" :keep-alive="true" :field-name="fieldName('type')" :required-field-values="'textarea'" > <a17-textfield label="Maximum length" :name="fieldName('maxLength')" type="number" note="Number of characters" in-store="value" ></a17-textfield></a17-connectorfield><a17-connectorfield :is-value-equal="true" :field-name="fieldName('type')" :required-field-values="'number'" > <a17-textfield label="Minimum value" :name="fieldName('minValue')" type="number" in-store="value" ></a17-textfield> <a17-textfield label="Maximum value" :name="fieldName('maxValue')" type="number" in-store="value" ></a17-textfield></a17-connectorfield><a17-connectorfield :is-value-equal="true" :field-name="fieldName('type')" :required-field-values="'date'" > <a17-datepicker label="Earliest date available for selection" :name="fieldName('minDate')" place-holder="Select date" clear in-store="date"
></a17-datepicker> <a17-datepicker label="Latest date available for selection" :name="fieldName('maxDate')" place-holder="Select date" clear in-store="date"
></a17-datepicker></a17-connectorfield><a17-connectorfield :is-value-equal="true" :field-name="fieldName('type')" :required-field-values="'file'" > <a17-locale type="a17-textfield" :attributes="{ label: 'Template file URL', name: fieldName('template'), type: 'text', note: 'Will be offered for download', inStore: 'value' }" ></a17-locale></a17-connectorfield>
    </div>
</template>

<script>
  import BlockMixin from '@/mixins/block'

  export default {
    mixins: [BlockMixin]
  }
</script>
